version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword123!
    ports:
      - "1433:1433"

  api:
    build: .
    container_name: mobile_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Tutaj jest klucz do sukcesu: nazwa musi pasowaÄ‡ do Twojego JSONa! [cite: 2026-01-14]
      - ConnectionStrings__DefaultConnection=Server=db;Database=CottageDB;User Id=sa;Password=myStrongPassword123!;TrustServerCertificate=True
    depends_on:
      - db